### PR TITLE
Fix parsing of recurring/repeating reinforcements directives

### LINKED ISSUE #45: SCENA008.INI:108: Invalid drop time string: '20+'
When playing Atreides mission 4 (other missions print that error as well), there are the following errors in the log:

```
INFO    :   SCENA008.INI:108: Invalid drop time string: '20+'!
INFO    :   SCENA008.INI:109: Invalid drop time string: '20+'!
INFO    :   SCENA008.INI:110: Invalid drop time string: '20+'!
INFO    :   SCENA008.INI:111: Invalid drop time string: '20+'!
```

After Atreides level 4, there is a cutscene where Emperor says that Harkonnen was unable to beat the player even with the help of Sardaukar. However during that level, there never were any Sardaukar troops. I wonder if that might be correlated with that error message.

### PR DESCRIPTION
**Pull request by juj**
Fix parsing of recurring/repeating reinforcements directives in INI files. Fixes #45. Also make an assumption that a previous parsed reinforcements format does not actually occur in the INI files.

### CODE REVIEW

**Comment by juj** [comment]
Yay, also fixes the issue that Sardaukar reinforcements were never seen:

image

**Comment by henricj** [comment]
Check the extra maps for ",+"; many use this construct:
https://sourceforge.net/projects/dunelegacy/files/maps/

There's another point I'm not sure about.  The scenario specification talks about how the original game ignores the "+" (which I interpret as ignoring the repetition, not the entire reinforcement line).  This suggests that one might want to have a configuration flag that determines if the use of the "N+" format should result in a repeat or not.

**Comment by juj** [comment]
Great catch! Indeed it looks like both forms are then used. Updated the PR to keep the parsing for both.

> This suggests that one might want to have a configuration flag that determines if the use of the "N+" format should result in a repeat or not.

Yeah, that might be a future feature. There are several minute differences between the original game, the game does not currently have a "keep original bugs" mode, so maybe this kind of thing would pile under such an option if one was to some day exist.

**Comment by henricj** [comment]
In order to help test loading scenario INI files, especially with the reinforcement "+", I've added another [test](https://github.com/henricj/dunelegacy/commit/9d49b3eac25f7ef50fabe635ad12ef3dc3cdf2ec) to [INIFileTestCase](https://github.com/henricj/dunelegacy/tree/modernize/tests/INIFileTestCase) that loads all the scenarios in the tree.  This test only fails if an exception is thrown, so all it really verifies is that a Game instance can be initialized (and it demonstrates both how using global variables inappropriately can make life difficult and how deeply entangled the UI and actual game code remain).  I'll see about adding some scenarios that deliberately try to confuse the parsing code.

The first `splitString()` call would succeed even if there was remaining data on the line, which prevented the second `splitString()` call from ever happening.  Therefore, the repeat flag was never set to true.  [This change](https://github.com/henricj/dunelegacy/commit/538504165c1d59dbb42533113c58155983196092) should resolve that problem.  https://github.com/henricj/dunelegacy/blob/752788769ab9de571199a294edb807b37ab2b540/src/INIMap/INIMapLoader.cpp#L790-L796
And no, I was not productive enough to add tests for the two `splitString()` overloads.

Every time I look at `INIMapLoader` and `INIMapEditorLoader` they just beg to be consolidated.  Not all of the code is the same between the two, but much of it is.  (Perhaps some intermediate `INIMapEditorBase` class or even an entirely separate class?)

**Comment by juj** [comment]
> the repeat flag was never set to true. [This change](https://github.com/henricj/dunelegacy/commit/538504165c1d59dbb42533113c58155983196092) should resolve that problem.

Nice! I only tested by playing the missions, and did not have patience to wait for 40 minutes to see several Sardaukars come in :)

**Pull request merged**
